export const FETCH_VIDEOLISTS = "FETCH_VIDEOLISTS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";